/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GladeButton: typeof import('./components/GladeButton/index.vue')['default']
    GladeButtonGroup: typeof import('./components/GladeButtonGroup/index.vue')['default']
    GladeColorPicker: typeof import('./components/GladeColorPicker/index.vue')['default']
    GladeContextMenu: typeof import('./components/GladeContextMenu/index.vue')['default']
    GladePopover: typeof import('./components/GladePopover/index.vue')['default']
    GladeSlider: typeof import('./components/GladeSlider/index.vue')['default']
  }
}
